const products = [
    {
      id: 1,
      name: "Raspberry Coconut Yog",
      image: "raspberry.jpg", // Replace with actual image URLs
      stock: 699,
      price: "3,59 EGP",
      category: "Yogurt",
      date: "2024/03/04 at 12:09 pm",
      isFeatured: false,
      oldPrice: null,
    },
    {
      id: 2,
      name: "Plain With Coconut",
      image: "plain.jpg",
      stock: 699,
      price: "2,19 EGP",
      category: "Yogurt",
      date: "2024/03/04 at 12:09 pm",
      isFeatured: true,
      oldPrice: null,
    },
    {
      id: 3,
      name: "Atlantic Salmon",
      image: "salmon.jpg",
      stock: 899,
      price: "7,68 EGP",
      category: "Fresh Fish",
      date: "2024/03/04 at 12:09 pm",
      isFeatured: false,
      oldPrice: null,
    },
    {
      id: 4,
      name: "Oat Milk With Vitamins",
      image: "oatmilk.jpg",
      stock: 699,
      price: "1,51 EGP",
      oldPrice: "2,16 EGP",
      category: "Milk & Cream",
      date: "2024/03/04 at 12:09 pm",
      isFeatured: false,
      editable: true,
    },
  ];